# Generated by Django 5.2.7 on 2025-11-07 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_task_completed_alter_task_description_and_more'),
    ]

    operations = [
    ]
